backend:
  name: github
  repo: anneschmidtco/privacydynamics
  branch: dev

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "Home"
        file: "site/pages/home.md"
        fields:
          - label: "Hero Section"
            name: "hero_section"
            widget: "object"
            fields:
              - label: "Header"
                name: "header"
                widget: "markdown"
              - label: "Animated Heading Strings"
                name: "animated_headings"
                widget: "string"
              - label: "Sub Header"
                name: "sub_header" 
                widget: "string"
              - label: "Button" 
                name: "button"
                widget: "object"
                fields:
                - label: "Text"
                  name: "text"
                - label: "Link"
                  name: "link"
              - label: "Image" 
                name: "image" 
                widget: "image"
          - label: "Features"
            name: 'features'
            widget: "list"
            fields:
              - label: "Tag"
                name: "tag"
                widget: "string"
              - label: "Icon"
                name: "icon"
                widget: "image"
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Description"
                name: "description"
                widget: "markdown"
          - label: "Distortion Section"
            name: "distortion_section"
            widget: "object"
            fields:
              - label: "Title" 
                name: "title"
                widget: "string"
              - label: "Sub Title"
                name: "sub_title" 
                widget: "markdown"
              - label: "Chart Image"
                name: "chart_image" 
                widget: "image"
          - label: "Stats Section"
            name: "stats_section"
            widget: "object"
            fields:
              - label: "CTA Text"
                name: "cta_text" 
                widget: "string"
              - label: Title 
                name: "title"
                widget: "markdown"
              - label: "Icon"
                name: "icon" 
                widget: "image"
              - label: "Stats"
                name: "stats"
                widget: "list"
                fields: 
                  - label: "Stat"
                    name: "stat"
                    widget: "string"
                  - label: "Description"
                    name: "description"
                    widget: "string"
          - label: "In Action Section"
            name: 'in_action_section'
            widget: "object"
            fields:
              - label: "Title"
                name: "title" 
                widget: "markdown"
              - label: "Icon"
                name: "icon" 
                widget: "image"
              - label: Button
                name: "button"
                widget: object
                fields:
                - label: Text
                  name: "text"
                - label: Link
                  name: "link"

      - label: "Product Page"
        name: "Product"
        file: "site/pages/product.md"
        fields:
          - label: "Hero Section"
            name: "hero_section"
            widget: "object"
            fields:
              - label: "Header"
                name: "header"
                widget: "markdown"
              - label: "Sub Header"
                name: "sub_header" 
                widget: "string"
              - label: "Button" 
                name: "button"
                widget: "object"
                fields:
                - label: "Text"
                  name: "text"
                - label: "Link"
                  name: "link"
              - label: "Image" 
                name: "image" 
                widget: "image"
          - label: "Experts Section"
            name: "experts_section"
            widget: "object"
            fields:
              - label: "Header"
                name: "header"
                widget: "string"
              - label: "Image" 
                name: "image" 
                widget: "image"
          - label: "Features"
            name: 'features'
            widget: "list"
            fields:
              - label: "Title"
                name: "title"
                widget: "markdown"
              - label: "Description"
                name: "description"
                widget: "markdown"
              - label: "Image"
                name: "image"
                widget: "image"
                required: false
          - label: "How It Works"
            name: 'hiw'
            widget: "object"
            fields:
              - label: "Header"
                name: "header"
                widget: "string"
              - label: "Sub Header"
                name: "sub_header" 
                widget: "string"
      - label: "Pricing Page"
        name: "Pricing"
        file: "site/pages/pricing.md"
        fields:
          - label: "Pricing Section"
            name: "pricing_section"
            widget: "object"
            fields:
              - label: "Header"
                name: "header"
                widget: "markdown"
              - label: "Sub Header"
                name: "sub_header" 
                widget: "string"
              - label: "Plans"
                name: 'plans'
                widget: "list"
                fields:
                  - label: "Name"
                    name: "name"
                    widget: "string"
                  - label: "Pricing"
                    name: "pricing"
                    widget: "string"
                  - label: "Plan Features"
                    name: "plan_features"
                    widget: "list"
                    fields:
                      - label: "Icon"
                        name: "icon"
                        widget: "select"
                        options: ["Yes", "No"]
                      - label: "Description"
                        name: "description"
                        widget: "markdown"
                  - label: "CTA Button"
                    name: "cta_button"
                    widget: "object"
                    fields: 
                      - label: "Text"
                        name: "text"
                      - label: "Link"
                        name: "link"
              - label: "Footer CTA"
                name: "footer_cta"
                widget: "object"
                fields:
                  - label: "Title"
                    name: "title"
                    widget: "string"
                  - label: "CTA Button"
                    name: "cta_button"
                    widget: "object"
                    fields: 
                      - label: "Text"
                        name: "text"
                      - label: "Link"
                        name: "link"
              - label: "Background Image"
                name: "background_image"
                widget: "image"

      - label: "About Page"
        name: "About"
        file: "site/pages/about.md"
        fields:
          - label: "Hero Section"
            name: "hero_section"
            widget: "object"
            fields:
              - label: "Header"
                name: "header"
                widget: "string"
              - label: "Sub Header"
                name: "sub_header" 
                widget: "string"
              - label: "Body"
                name: "body" 
                widget: "text"
          - label: "Values Section"
            name: "values_section"
            widget: "object"
            fields:
              - label: "Header"
                name: "header"
                widget: "string"
              - label: "Values"
                name: "values" 
                widget: "list"
                fields:
                  - label: "Title"
                    name: "title"
                    widget: "string"
                  - label: "Body"
                    name: "body"
                    widget: "text"
          - label: "Mission Section"
            name: "mission_section"
            widget: "object"
            fields:
              - label: "Header"
                name: "header"
                widget: "text"
              - label: "Sub Header"
                name: "sub_header"
                widget: "text"
          - label: "Team Section"
            name: "team_section"
            widget: "object"
            fields:
              - label: "Header"
                name: "header"
                widget: "string"
              - label: "Sub Header"
                name: "sub_header"
                widget: "string"
              - label: "Body"
                name: "body"
                widget: "text"
              - label: "Tags"
                name: "tags"
                widget: "string"
          - label: "Leaders Section"
            name: "leaders_section"
            widget: "object"
            fields:
              - label: "Header"
                name: "header"
                widget: "text"
              - label: "Leaders"
                name: "leaders"
                widget: "list"
                fields:
                  - label: "Profile"
                    name: "profile"
                    widget: "image"
                  - label: "Name"
                    name: "name"
                    widget: "string"
                  - label: "Title"
                    name: "title"
                    widget: "string"
          - label: "Investors Section"
            name: "investors_section"
            widget: "object"
            fields:
              - label: "Header"
                name: "header"
                widget: "text"
              - label: "Investors"
                name: "investors"
                widget: "list"
                fields:
                  - label: "Logo"
                    name: "logo"
                    widget: "image"
              - label: "Other Header"
                name: "other_header"
                widget: "string"
              - label: "Other Investors"
                name: "other_investors"
                widget: "list"
                fields:
                  - label: "Logo"
                    name: "logo"
                    widget: "image"
          - label: "Media Section"
            name: "media_section"
            widget: "object"
            fields:
              - label: "Header"
                name: "header"
                widget: "string"
              - label: "Press Releases"
                name: "press_releases"
                widget: "list"
                fields:
                  - label: "Title"
                    name: "title"
                    widget: "string"
                  - label: "Excerpt"
                    name: "excerpt"
                    widget: "text"
                  - label: "Link"
                    name: "link"
                    widget: "string"
                  - label: "Date"
                    name: "date"
                    widget: "date"
              - label: "Contact"
                name: "contact"
                widget: "object"
                fields:
                  - label: "Header"
                    name: "header"
                    widget: "string"
                  - label: "Email"
                    name: "email"
                    widget: "string"
          - label: "CTA Section"
            name: "cta_section"
            widget: "object"
            fields:
              - label: "Header"
                name: "header"
                widget: "markdown"
              - label: "Sub Header"
                name: "sub_header"
                widget: "markdown"  

      - label: "Careers Page"
        name: "Careers"
        file: "site/pages/careers.md"
        fields:
          - label: "Hero Section"
            name: "hero_section"
            widget: "object"
            fields:
              - label: "Header"
                name: "header"
                widget: "string"
              - label: "Sub Header"
                name: "sub_header" 
                widget: "string"
              - label: "Body"
                name: "body" 
                widget: "text"
          - label: "Job Openings Section"
            name: "openings_section"
            widget: "object"
            fields:
              - label: "Header"
                name: "header"
                widget: "string"
              - label: "Job Openings"
                name: "openings" 
                widget: "object"
                fields:
                  - label: "Categories"
                    name: "categories"
                    widget: "list"
                    fields:
                    - label: "Title"
                      name: "title"
                      widget: "string"
                    - label: "Jobs"
                      name: "jobs"
                      widget: "list"
                      fields:
                      - label: "Title"
                        name: "title"
                        widget: "string"
                      - label: "Link"
                        name: "link"
                        widget: "string"
                      - label: "Location"
                        name: "location"
                        widget: "string"
              - label: "All Jobs Link"
                name: "all_jobs_link" 
                widget: "object"
                fields: 
                  - label: "Text"
                    name: "text"
                  - label: "Link"
                    name: "link"
              - label: "Sub Header"
                name: "sub_header" 
                widget: "string"
              - label: "Body"
                name: "body" 
                widget: "text"
          - label: "Benefits Section"
            name: "benefits_section"
            widget: "object"
            fields:
              - label: "Header"
                name: "header"
                widget: "string"
              - label: "Benefits"
                name: "benefits" 
                widget: "list"
                fields:
                  - label: "Title"
                    name: "title"
                    widget: "string"
                  - label: "Body"
                    name: "body"
                    widget: "text"
      
      - label: "Resources Page"
        name: "Resources"
        file: "site/pages/resources.md"
        fields:
          - label: "Hero Section"
            name: "hero_section"
            widget: "object"
            fields:
              - label: "Header"
                name: "header"
                widget: "string"
              - label: "Background Image"
                name: "background_image" 
                widget: "image"
          - label: "Categories"
            name: "categories"
            widget: "list"
            fields:
              - label: "Name"
                name: "name"
                widget: "string"
              - label: "Sub Categories"
                name: sub_categories
                widget: list
                fields:
                  - label: "Name"
                    name: "name"
                    widget: "string"

  - name: "categories"
    label: "Categories"
    folder: "site/categories"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Name" 
        name: "name"
        widget: "string"
  - name: "resources"
    label: "Resources"
    folder: "site/resources"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Heading" 
        name: "heading"
        widget: "string"
      - label: "Title" 
        name: "title"
        widget: "string"
      - label: "Excerpt"
        name: "excerpt" 
        widget: "string"
      - label: "Publish Date" 
        name: "date" 
        widget: "date"
      - label: "Category"
        name: "category"
        widget: "relation"
        collection: "categories"
        search_fields: ['name']
        value_field: "name"
        display_fields: ["{{name}}"]
      - label: "Body" 
        name: "body" 
        widget: "markdown"
      - label: "Download Button"
        name: "download_button"
        widget: "object"
        required: false
        fields: 
          - label: "Text"
            name: "text"
          - label: "Link"
            name: "link"

  - label: "Settings"
    name: "settings"
    files:
      - label: "General Settings"
        name: "Settings"
        collapsed: false
        delete: false
        editor:
          preview: false
        file: "site/settings.md"
        fields:
          - label: "Site Logo"
            name: "logo"
            widget: "image"
          - label: "Site Footer Logo"
            name: "footer_logo"
            widget: "image"
          - label: "Site Title"
            name: "site_title"
            widget: "markdown"

  